### ISSUE TITLE
InvalidCastException: Specified cast is not valid.

### ISSUE THREAD

**Issue by jacquesleemans** [myanko/uvs-finder#27]
Unity version: 2021.2.15f1

Stack trace:

InvalidCastException: Specified cast is not valid.
Unity.VisualScripting.UVSFinder.UVSFinder.FindElementsInStateGraph (Unity.VisualScripting.UVSFinder.ResultItem resultItem, Unity.VisualScripting.GraphWindow graphWindow, Unity.VisualScripting.StateGraph stateGraph) (at Assets/com.sokatoa.uvs.finder/Editor/UVSFinder.cs:326)
Unity.VisualScripting.UVSFinder.UVSFinder.SelectElementInStateGraph (Unity.VisualScripting.UVSFinder.ResultItem resultItem) (at Assets/com.sokatoa.uvs.finder/Editor/UVSFinder.cs:304)
Unity.VisualScripting.UVSFinder.UVSFinder.SelectElement (Unity.VisualScripting.UVSFinder.ResultItem resultItem) (at Assets/com.sokatoa.uvs.finder/Editor/UVSFinder.cs:273)
Unity.VisualScripting.UVSFinder.UVSFinder.OnItemsChosen (System.Collections.Generic.IEnumerable`1[T] itemsChosen) (at Assets/com.sokatoa.uvs.finder/Editor/UVSFinder.cs:218)
UnityEngine.UIElements.BaseVerticalCollectionView.NotifyOfSelectionChange () (at <13f9cfbfcaea4d30a66e97eb510cfa62>:0)
UnityEngine.UIElements.BaseVerticalCollectionView.SetSelectionInternal (System.Collections.Generic.IEnumerable`1[T] indices, System.Boolean sendNotification) (at <13f9cfbfcaea4d30a66e97eb510cfa62>:0)
UnityEngine.UIElements.BaseVerticalCollectionView.SetSelection (System.Collections.Generic.IEnumerable`1[T] indices) (at <13f9cfbfcaea4d30a66e97eb510cfa62>:0)
UnityEngine.UIElements.BaseVerticalCollectionView.SetSelection (System.Int32 index) (at <13f9cfbfcaea4d30a66e97eb510cfa62>:0)
UnityEngine.UIElements.BaseVerticalCollectionView.DoSelect (UnityEngine.Vector2 localPosition, System.Int32 clickCount, System.Boolean actionKey, System.Boolean shiftKey) (at <13f9cfbfcaea4d30a66e97eb510cfa62>:0)
UnityEngine.UIElements.BaseVerticalCollectionView.ProcessPointerDown (UnityEngine.UIElements.IPointerEvent evt) (at <13f9cfbfcaea4d30a66e97eb510cfa62>:0)
UnityEngine.UIElements.BaseVerticalCollectionView.OnPointerDown (UnityEngine.UIElements.PointerDownEvent evt) (at <13f9cfbfcaea4d30a66e97eb510cfa62>:0)
UnityEngine.UIElements.EventCallbackFunctor`1[TEventType].Invoke (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.PropagationPhase propagationPhase) (at <13f9cfbfcaea4d30a66e97eb510cfa62>:0)
UnityEngine.UIElements.EventCallbackRegistry.InvokeCallbacks (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.PropagationPhase propagationPhase) (at <13f9cfbfcaea4d30a66e97eb510cfa62>:0)
UnityEngine.UIElements.CallbackEventHandler.HandleEvent (UnityEngine.UIElements.EventBase evt) (at <13f9cfbfcaea4d30a66e97eb510cfa62>:0)
UnityEngine.UIElements.EventDispatchUtilities.PropagateEvent (UnityEngine.UIElements.EventBase evt) (at <13f9cfbfcaea4d30a66e97eb510cfa62>:0)
UnityEngine.UIElements.PointerEventDispatchingStrategy.SendEventToTarget (UnityEngine.UIElements.EventBase evt) (at <13f9cfbfcaea4d30a66e97eb510cfa62>:0)
UnityEngine.UIElements.PointerEventDispatchingStrategy.DispatchEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <13f9cfbfcaea4d30a66e97eb510cfa62>:0)
UnityEngine.UIElements.EventDispatcher.ApplyDispatchingStrategies (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, System.Boolean imguiEventIsInitiallyUsed) (at <13f9cfbfcaea4d30a66e97eb510cfa62>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <13f9cfbfcaea4d30a66e97eb510cfa62>:0)
UnityEngine.UIElements.EventDispatcher.Dispatch (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, UnityEngine.UIElements.DispatchMode dispatchMode) (at <13f9cfbfcaea4d30a66e97eb510cfa62>:0)
UnityEngine.UIElements.BaseVisualElementPanel.SendEvent (UnityEngine.UIElements.EventBase e, UnityEngine.UIElements.DispatchMode dispatchMode) (at <13f9cfbfcaea4d30a66e97eb510cfa62>:0)
UnityEngine.UIElements.UIElementsUtility.DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) (at <13f9cfbfcaea4d30a66e97eb510cfa62>:0)
UnityEngine.UIElements.UIElementsUtility.UnityEngine.UIElements.IUIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& eventHandled) (at <13f9cfbfcaea4d30a66e97eb510cfa62>:0)
UnityEngine.UIElements.UIEventRegistration.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at <13f9cfbfcaea4d30a66e97eb510cfa62>:0)
UnityEngine.UIElements.UIEventRegistration+<>c.<.cctor>b__1_2 (System.Int32 i, System.IntPtr ptr) (at <13f9cfbfcaea4d30a66e97eb510cfa62>:0)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& result) (at <b2402a089b6342f69ac2b0aa0047472d>:0)

**Comment by myanko** [comment]
Can you describe what you tried to do?

**Comment by etherElric** [comment]
It's probably fixed with the latest commits. 
If it happens again, please make sure to tell us what is the type of node you were trying to search or select.
Thank you
