### ISSUE TITLE
Current graph section change the selected object current graph in the graph window

### ISSUE THREAD

**Issue by myanko** [myanko/uvs-finder#29]
When you have a graph opened from an object in the hierarchy, the graph window link to GO > GraphAsset/s. But when you search click on an item in the CurrentGraph list, it just open the Graph and break the link to the current object from witch it was opened.

![image](https://user-images.githubusercontent.com/7476211/162211792-d220e667-a6e0-4963-bc62-238b406dd82e.png)

**Comment by etherElric** [comment]
Fixed:a2228276695d466ddb20fed83798ebc05ec3a5a3
