### ISSUE TITLE
Window partially un-docks after restoring

### ISSUE THREAD

**Issue by nrichards** [myanko/uvs-finder#40]
1. When I dock the window:
2. <img width="650" alt="image" src="https://user-images.githubusercontent.com/704698/183275762-aa987a4a-ba83-4c1e-9228-5695e318f2ba.png">
3. then I maximize a different window (via Shift+Space or double-clicking on the window tab's name)
4. then I restore the editor windows, again Shift+Space
5. the UVS finder window partially un-docks, showing no search results 
6. <img width="465" alt="image" src="https://user-images.githubusercontent.com/704698/183275805-1e790166-bd99-4808-85fd-6000efec7726.png">
7. clicking to focus on the duplicate docked tab causes the floating undocked window to redraw incorrectly
8. <img width="976" alt="image" src="https://user-images.githubusercontent.com/704698/183275831-cf9dcc62-0306-4359-bdf0-038a3ecc0969.png">

**Comment by myanko** [comment]
This bug should now be fixed with the version 0.4.

**Comment by nrichards** [comment]
Sweet - thank you @myanko for the handy tool.
